import React from "react"
import { Header } from "../ui/compositions/Headers/Headers"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Header,
  "https://www.figma.com/design/PxA2x3qTLJjlSZ2TfExZFS?node-id=2287%3A22651",
  {
    props: {
      platform: figma.enum("Platform", {
        Desktop: "desktop",
        Mobile: "mobile",
      }),
      state: figma.enum("State", {
        Open: "open",
        Default: "default",
      }),
    },
    example: (props) => <Header />,
  },
)
