import React from "react"
import { Search } from "../ui/primitives/Search/Search"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Search,
  "https://www.figma.com/design/PxA2x3qTLJjlSZ2TfExZFS?node-id=2236%3A14989",
  {
    props: {
      value: figma.string("Value"),
      state: figma.enum("State", {
        Default: "default",
        Disabled: "disabled",
      }),
      valueType: figma.enum("Value Type", {
        Default: "default",
        Placeholder: "placeholder",
      }),
    },
    example: (props) => <Search />,
  },
)
